language: node_js
cache: yarn
notifications:
  email: false
env:
  - TEST=test
node_js:
  - lts/*
  - node
install: yarn install
script:
  - yarn validate
after_success:
  - mv packages/react-image/coverage/coverage-final.json
    packages/react-image/coverage/coverage.json
branches:
  only:
    - master
    - next
    - beta

jobs:
  include:
    - stage: release
      # if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      if: branch = master AND type != pull_request
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - yarn build
      after_success:
        - echo "Deploying to npm ..."
        - yarn semantic-release

    - stage: deploy
      if: branch = master AND type != pull_request
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - echo "Deploying to github pages ..."
        - yarn storybook:build
      deploy:
        provider: pages
        local_dir: packages/react-image/.storybook-static
        cleanup: false
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
